modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="recmod"
version="${mod_version}"
displayName="REC: Paranormal Mechanics"
authors="Hamilton"
description='''
Mod de mecânicas de fita VHS e terror para o Vhsworld.
'''

[[dependencies.recmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.recmod]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="recmod.mixins.json"
